CREATE TABLE [CodigoQualificacaoAssinante](
    [ID_CODIGO] INT IDENTITY (1,1) NOT NULL,
    [ID] [varchar] (5) NOT NULL,
    [DESCRICAO] [varchar] (255) NOT NULL
)


CREATE TABLE [TBL_Abertura_Temporaria](
    [ID_USUARIO] INT IDENTITY (1,1) NOT NULL,
    [USUARIO] VARCHAR (255) NOT NULL,
    [OBRA] VARCHAR (255) NOT NULL,
    [MODULO] VARCHAR (255) NOT NULL,
    [FORMULARIO] VARCHAR (255) NOT NULL,
    [DATA_BLOQUEIO_FINANCEIRO] DATETIME NOT NULL,
    [DATA_CONTAB_FECHADA] DATETIME NOT NULL,
    [DATA_INICIAL] DATETIME NOT NULL,
    [DATA_FINAL] DATETIME NOT NULL,
    [DATA_EXPIRACAO] DATETIME NOT NULL,
    [STATUS] VARCHAR (255) NOT NULL
)

CREATE TABLE [TBL_Log_Abertura](
    [ID_LOG] INT IDENTITY (1,1) NOT NULL,
    [ID] INT NOT NULL,
    [USUARIO] VARCHAR (255) NOT NULL,
    [MODULO] VARCHAR (255) NOT NULL,
    [DESCRICAO] VARCHAR (255) NOT NULL
)

CREATE TABLE [TBL_MODULO_FORM](
    [ID] INT IDENTITY (1,1) NOT NULL,
    [NOME_MODULO] VARCHAR (255) NOT NULL,
    [NOME_FORMULARIO] VARCHAR (255) NOT NULL
)

