CREATE TABLE [TBL_MODULO_FORM](
    [ID] INT IDENTITY (1,1) NOT NULL,
    [NOME_MODULO] VARCHAR (255) NOT NULL,
    [NOME_FORMULARIO] VARCHAR (255) NOT NULL
);

INSERT INTO TBL_MODULO_FORM(NOME_MODULO, NOME_FORMULARIO)
VALUES ('Títulos a Pagar','Assistente de Digitação Títulos a Pagar');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO, NOME_FORMULARIO)
VALUES ('Títulos a Pagar','Pesquisa de Títulos a Pagar');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO, NOME_FORMULARIO)
VALUES ('Títulos a Pagar','Títulos a Pagar');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO, NOME_FORMULARIO)
VALUES ('Títulos a Receber','Pesquisa de Títulos');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO,NOME_FORMULARIO)
VALUES ('Títulos a Receber','Títulos a Receber');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO,NOME_FORMULARIO)
VALUES ('Controle Bancário', 'Movimento Bancário');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO,NOME_FORMULARIO)
VALUES ('Controle Bancário','Débito Automático');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO,NOME_FORMULARIO)
VALUES ('Controle Bancário','Emissão de Cheques');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO,NOME_FORMULARIO)
VALUES ('Controle Bancário','Emissão de Borderô');

INSERT INTO TBL_MODULO_FORM(NOME_MODULO,NOME_FORMULARIO)
VALUES ('Controle de Incorporações','Baixa de pagamentos')
